stages:
  - build

services:
  - docker:19.03.8-dind

build-docker:
  stage: build
  image: docker:19.03.8
  tags:
    - docker
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
