version: '3.1'

services:
  mariadb:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST
      - PMA_USER
      - PMA_PASSWORD
#    restart: always
    ports:
      - '8000:80'
    volumes:
      - /sessions

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
      - '1025:25'

  node:
    build: ./docker/node
    tty: true
    ports:
      - "3000:3000" # <host-port>:<container-port> to listen to, so anything running on port 3000 of the container will map to port 3000 on our localhost
      - "8080:8080"
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./www:/var/www

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www

volumes:
  mysql_data:
